---
- name: Install tmux on Ubuntu
  apt:
    name: tmux
    state: present
  when: "ansible_distribution == 'Ubuntu'"

- name: Install tmux on Redhat
  yum:
      name: tmux
      state: present
  when: "ansible_distribution == 'Redhat'"

- name: Install tmux on CentOS
  yum:
      name: tmux
      state: present
  when: "ansible_distribution == 'CentOS'"

- name: Configure term
  lineinfile:
    create=yes
    path=~/.bashrc
    line="alias tmux='TERM=screen-256color-bce tmux'"
    state=present

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
